-- MySQL Script generated by MySQL Workbench
-- Mon Aug 13 13:55:50 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Patrimonio_Comunicacao
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Patrimonio_Comunicacao
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Patrimonio_Comunicacao` DEFAULT CHARACTER SET utf8 ;
USE `Patrimonio_Comunicacao` ;

-- -----------------------------------------------------
-- Table `Patrimonio_Comunicacao`.`Patrimonio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Patrimonio_Comunicacao`.`Patrimonio` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(60) NOT NULL,
  `Numero` VARCHAR(20) NULL,
  `Qualidade` VARCHAR(20) NULL,
  `Ocupado` TINYINT(1) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Patrimonio_Comunicacao`.`Requerente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Patrimonio_Comunicacao`.`Requerente` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(60) NOT NULL,
  `Endereco` VARCHAR(60) NULL,
  `Cidade` VARCHAR(45) NULL,
  `Telefone` VARCHAR(20) NULL,
  `Email` VARCHAR(45) NULL,
  `Nascimento` DATE NULL,
  `Ra` VARCHAR(10) NULL,
  `RG` VARCHAR(20) NULL,
  `CPF` VARCHAR(20) NULL,
  `Curso` VARCHAR(45) NULL,
  `Bloqueio` TINYINT(1) NULL,
  `Senha` VARCHAR(20) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Patrimonio_Comunicacao`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Patrimonio_Comunicacao`.`Usuario` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(60) NULL,
  `Cpf` VARCHAR(20) NULL,
  `Rg` VARCHAR(20) NULL,
  `Nascimento` DATE NULL,
  `Telefone` VARCHAR(20) NULL,
  `Celular` VARCHAR(20) NULL,
  `Login` VARCHAR(20) NULL,
  `Senha` VARCHAR(20) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Patrimonio_Comunicacao`.`Emprestimo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Patrimonio_Comunicacao`.`Emprestimo` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `IdRequerente` INT NOT NULL,
  `IdUsuario` INT NOT NULL,
  `Professor` VARCHAR(70) NULL,
  `Descricao` VARCHAR(200) NULL,
  `Hora` TIME NULL,
  `DataEmprestimo` DATE NULL,
  `DataPrevista` DATE NULL,
  `DataDevolucao` DATE NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Venda_Cliente1_idx` (`IdRequerente` ASC),
  INDEX `fk_Venda_Funcionario1_idx` (`IdUsuario` ASC),
  CONSTRAINT `fk_Venda_Cliente1`
    FOREIGN KEY (`IdRequerente`)
    REFERENCES `Patrimonio_Comunicacao`.`Requerente` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venda_Funcionario1`
    FOREIGN KEY (`IdUsuario`)
    REFERENCES `Patrimonio_Comunicacao`.`Usuario` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Patrimonio_Comunicacao`.`ItemEmprestimo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Patrimonio_Comunicacao`.`ItemEmprestimo` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `IdEmprestimo` INT NOT NULL,
  `IdPatrimonio` INT NOT NULL,
  `Qualidade` VARCHAR(20) NULL,
  `Quantidade` INT NULL,
  `Devolvido` TINYINT(1) NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Produto_has_Venda_Venda1_idx` (`IdEmprestimo` ASC),
  INDEX `fk_Produto_has_Venda_Produto1_idx` (`IdPatrimonio` ASC),
  CONSTRAINT `fk_Produto_has_Venda_Produto1`
    FOREIGN KEY (`IdPatrimonio`)
    REFERENCES `Patrimonio_Comunicacao`.`Patrimonio` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_has_Venda_Venda1`
    FOREIGN KEY (`IdEmprestimo`)
    REFERENCES `Patrimonio_Comunicacao`.`Emprestimo` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Patrimonio_Comunicacao`.`Log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Patrimonio_Comunicacao`.`Log` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Data` DATE NULL,
  `Hora` TIME NULL,
  `Acao` VARCHAR(60) NULL,
  `Requerente` VARCHAR(60) NULL,
  `Usuario` VARCHAR(60) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
